name = "epigraphs"
uuid = "d2a11b8e-ad96-4124-ae14-fb55adc2dea6"
authors = ["Mathijs Schuurmans <mathijs.schuurmans@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
